DEFAULT_MARKETING_TEMPLATE = r"M:\Project Folder Templates\Project Number - Project Name - For Marketing Drive"
DEFAULT_WORK_TEMPLATE = r"M:\Project Folder Templates\Project Number - Project Name"
DEFAULT_BD_TARGET = r"V:\\"
DEFAULT_WORK_TARGET = r"W:\\"
FOLDER_TO_DELETE = "1 Marketing"